### ISSUE TITLE
Input Hash stimmt nicht überein

### ISSUE THREAD

**Issue by Halderim** [touchdesign/prestashop-sofortbanking#3]
Ich setze in drei Shops Sofortbanking ein. Alle drei Shops sind auf der gleichen Version von Prestashop 1.6.1.4, in zwei Shops wird der Input Hash welcher durch durch SHA1 generiert wird korrekt erzeugt im dritten Shop hingegen nicht.

Lässt man sich den String welcher durch implode('|', $parameters) erzeugt wird ausgeben und lässt man diesen durch sha1() oder einen anderen SHA1 Generator hashen ist der Hash nicht gleich dem Hash welcher im Modul erzeugt wird. Das führte dazu das alle Bezahlungen bei Sofort abgelehnt wurden.

Beim debuggen des Codes und des Templates payment_redirect.tpl ist aufgefallen das der Parameter reason_2 mehrere Whitespaces beinhaltete welche dazu führten das der Name Max Muster nicht 10 Zeichen lang war sondern 12. Das Formular welches diesen Parameter an Sofort schickt hat diese Zeichen nicht mehr somit stimmen die Hashes nicht überein.

Ich habe Vor- und Nachname mit einem trim versehen welches das Problem gelöst hat.

Vielleicht sollte das Trim generell hier verwendet werden. Woher diese Leer bzw. unsichtbaren Zeichen  stammen konnte ich nicht reproduzieren.

Betreffende Zeile ist 88 in der Datei controllers/front/payment.php

**Comment by christingruber** [comment]
Danke für dein Feedback @Halderim fixed 812d372. Wir konnten das Problem in unserer Testumgebung nicht reproduzieren haben uns aber dazu entschieden die Werte generell einmal zu trimmen.
