### ISSUE TITLE
Problem after Update from 2.5.7 to 3.0

### ISSUE THREAD

**Issue by page6de** [touchdesign/prestashop-sofortbanking#8]
We've just updated the plugin and noticed, that some settings were missing (The whole Step 2: "Einrichtung eines Projektes"). Furthermore some other settings changed and we always get the Message, that this module is not properly configured "SOFORT Überweisung: Die Modulkonfiguration ist unvollständig."

**Comment by christingruber** [comment]
It's a regular support question "module configuration error", so we close this issue. The [SOFORT team](https://www.sofort.com/eng-INT/merchant/contact/) will be available if you need help.
